"""add estimated_hours to tickets and agent_decisions

Revision ID: 005_add_estimated_hours
Revises: 004_agent_decisions
Create Date: 2026-03-28 16:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005_add_estimated_hours'
down_revision: Union[str, None] = '004_agent_decisions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_decisions', sa.Column('estimated_hours', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('estimated_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'estimated_hours')
    op.drop_column('agent_decisions', 'estimated_hours')
    # ### end Alembic commands ###
