"""ticket_relations

Revision ID: 31b5ef1ff824
Revises: 005_add_estimated_hours
Create Date: 2026-03-28 20:08:03.384820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b5ef1ff824'
down_revision: Union[str, None] = '005_add_estimated_hours'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_decisions_action'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_created_at'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_ticket_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_sprints_state'), table_name='sprints')
    op.add_column('tickets', sa.Column('related_ticket_id', sa.UUID(), nullable=True))
    op.add_column('tickets', sa.Column('relation_type', sa.String(), nullable=True))
    op.drop_index(op.f('ix_tickets_sprint_id'), table_name='tickets')
    op.create_foreign_key(None, 'tickets', 'tickets', ['related_ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_index(op.f('ix_tickets_sprint_id'), 'tickets', ['sprint_id'], unique=False)
    op.drop_column('tickets', 'relation_type')
    op.drop_column('tickets', 'related_ticket_id')
    op.create_index(op.f('ix_sprints_state'), 'sprints', ['state'], unique=False)
    op.create_index(op.f('ix_agent_decisions_ticket_id'), 'agent_decisions', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_created_at'), 'agent_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_decisions_action'), 'agent_decisions', ['action'], unique=False)
    # ### end Alembic commands ###
